// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qebrkzboqpdgpkwqpadq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlYnJremJvcXBkZ3Brd3FwYWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMjI0MTAsImV4cCI6MjA3ODg5ODQxMH0.8QgzPN1AtnegxqXEtaCbNbg6-hHLYNDSvLnQXGI7l0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});